# Generated by Django 3.2.5 on 2022-07-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
