# Generated by Django 3.2.5 on 2021-08-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'سایز', 'verbose_name_plural': 'سایزها'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='color',
        ),
        migrations.RemoveField(
            model_name='size',
            name='product_size',
        ),
        migrations.RemoveField(
            model_name='size',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(null=True, related_name='product', to='product.Color', verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(null=True, related_name='product', to='product.Size', verbose_name='اندازه'),
        ),
        migrations.AddField(
            model_name='size',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='size_product',
            field=models.CharField(choices=[('Extra Small', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL'), ('Double Large', 'XXL'), ('Triple Large', 'XXXL')], max_length=120, null=True),
        ),
    ]
