# Generated by Django 3.2.5 on 2022-07-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
