# Generated by Django 3.2.5 on 2021-08-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210802_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('f', 'محصولات ویژه'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
