# Generated by Django 3.2.5 on 2021-08-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210802_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس'), ('f', 'محصولات ویژه')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
