# Generated by Django 3.2.5 on 2021-08-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس'), ('f', 'محصولات ویژه')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='size',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
