# Generated by Django 3.2.5 on 2021-08-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210804_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('f', 'محصولات ویژه'), ('d', 'پیش نویس'), ('p', 'انتشار')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
