# Generated by Django 3.2.5 on 2021-08-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس'), ('f', 'محصولات ویژه')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
