# Generated by Django 3.2.5 on 2021-08-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210805_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('f', 'محصولات ویژه'), ('p', 'انتشار')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
