# Generated by Django 3.2.5 on 2021-08-09 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210809_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'تغییر', 'verbose_name_plural': 'تغییرات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('f', 'محصولات ویژه'), ('p', 'انتشار'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(blank=True, choices=[('Extra Small', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL'), ('Double Large', 'XXL'), ('Triple Large', 'XXXL')], max_length=20, null=True, verbose_name='سایز'),
        ),
    ]
