# Generated by Django 3.2.5 on 2021-08-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20210809_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color', unique=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(blank=True, choices=[('Extra Small', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL'), ('Double Large', 'XXL'), ('Triple Large', 'XXXL')], max_length=20, null=True, unique=True, verbose_name='سایز'),
        ),
    ]
