# Generated by Django 3.2.5 on 2021-08-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20210809_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('f', 'محصولات ویژه'), ('p', 'انتشار')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='رنگ'),
        ),
    ]
