# Generated by Django 3.2.5 on 2021-08-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20210809_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار'), ('f', 'محصولات ویژه')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
