# Generated by Django 3.2.5 on 2021-08-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20210823_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(null=True, to='product.Color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=50, verbose_name='کد رنگ'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام رنگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
