# Generated by Django 3.2.5 on 2021-08-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210826_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='product.Color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'انتشار')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
