# Generated by Django 3.2.5 on 2021-09-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_product_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visits',
            field=models.ManyToManyField(blank=True, related_name='product', to='product.IpAddress', verbose_name='تعداد بازدید ها'),
        ),
    ]
