# Generated by Django 3.2.5 on 2022-07-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('sending', 'درحال ارسال'), ('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('delivered', 'تحویل')], default='unpaid', max_length=15, verbose_name='وضعیت'),
        ),
    ]
