# Generated by Django 3.2.5 on 2021-08-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ادرس'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AddField(
            model_name='order',
            name='plaque',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='پلاک'),
        ),
        migrations.AddField(
            model_name='order',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='واحد'),
        ),
    ]
