# Generated by Django 3.2.5 on 2021-08-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_status'),
        ('order', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'تحویل'), ('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('sending', 'درحال ارسال')], default='unpaid', max_length=15, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='product.product', verbose_name='محصول'),
            preserve_default=False,
        ),
    ]
