# Generated by Django 3.2.5 on 2021-08-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20210823_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'پرداخت شده'), ('sending', 'درحال ارسال'), ('delivered', 'تحویل'), ('unpaid', 'پرداخت نشده')], default='unpaid', max_length=15, verbose_name='وضعیت'),
        ),
    ]
