# Generated by Django 3.2.5 on 2021-08-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='سفید', max_length=50, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('delivered', 'تحویل'), ('sending', 'درحال ارسال')], default='unpaid', max_length=15, verbose_name='وضعیت'),
        ),
    ]
