# Generated by Django 3.2.5 on 2021-08-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20210827_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='سفید', max_length=50, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('sending', 'درحال ارسال'), ('unpaid', 'پرداخت نشده'), ('delivered', 'تحویل'), ('paid', 'پرداخت شده')], default='unpaid', max_length=15, verbose_name='وضعیت'),
        ),
    ]
